### ISSUE TITLE
Homebridge Exiting, no permissions

### ISSUE THREAD

**Issue by InZan3** [manfredipist/homebridge-gpio-rgb-ledstrip#1]
Any Help for that?
`Aug 14 20:44:06 raspberrypi homebridge[1152]: [8/14/2019, 8:44:06 PM] [Bedroom LedStrip] Initializing SmartLedStrip accessory...
Aug 14 20:44:06 raspberrypi homebridge[1152]: 2019-08-14 20:44:06 initCheckPermitted:
Aug 14 20:44:06 raspberrypi homebridge[1152]: +---------------------------------------------------------+
Aug 14 20:44:06 raspberrypi homebridge[1152]: |Sorry, you don't have permission to run this program.    |
Aug 14 20:44:06 raspberrypi homebridge[1152]: |Try running as root, e.g. precede the command with sudo. |
Aug 14 20:44:06 raspberrypi homebridge[1152]: +---------------------------------------------------------+
Aug 14 20:44:06 raspberrypi homebridge[1152]: [8/14/2019, 8:44:06 PM] Error: pigpio error -1 in gpioInitialise
Aug 14 20:44:06 raspberrypi homebridge[1152]:     at initializePigpio (/usr/local/lib/node_modules/homebridge-gpio-rgb-ledstrip/node_modules/pigpio/pigpio.js:17:12)
Aug 14 20:44:06 raspberrypi homebridge[1152]:     at new Gpio (/usr/local/lib/node_modules/homebridge-gpio-rgb-ledstrip/node_modules/pigpio/pigpio.js:42:5)
Aug 14 20:44:06 raspberrypi homebridge[1152]:     at new SmartLedStripAccessory (/usr/local/lib/node_modules/homebridge-gpio-rgb-ledstrip/index.js:27:16)
Aug 14 20:44:06 raspberrypi homebridge[1152]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)
Aug 14 20:44:06 raspberrypi homebridge[1152]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
Aug 14 20:44:06 raspberrypi homebridge[1152]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Aug 14 20:44:06 raspberrypi homebridge[1152]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Aug 14 20:44:06 raspberrypi homebridge[1152]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Aug 14 20:44:06 raspberrypi homebridge[1152]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Aug 14 20:44:06 raspberrypi homebridge[1152]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Aug 14 20:44:06 raspberrypi homebridge[1152]: [8/14/2019, 8:44:06 PM] Got SIGTERM, shutting down Homebridge...
Aug 14 20:44:11 raspberrypi homebridge[1152]: [8/14/2019, 8:44:11 PM] [Config] Console v4.5.2 is listening on :: port 8080
Aug 14 20:44:11 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Aug 14 20:44:11 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
`

**Comment by manfredipist** [comment]
Have you already tried running homebridge as root? pigpio needs higher privileges to control GPIO

**Comment by InZan3** [comment]
Thank you for the fast reply :-)
How can i run Homebridge as root? Im a newby

**Comment by manfredipist** [comment]
Just run “sudo homebridge” 😉

**Comment by InZan3** [comment]
I Start Homebridge as Service with:
sudo systemctl start homebridge

**Comment by manfredipist** [comment]
Mmm i’m not sure if starting homebridge in that way can provide sufficient permissions for pigpio to work properly, i world try just running “sudo homebridge “
If that works i think you can set permissions directly to node by running “chmod u+s /usr/bin/node” but i can’t verify it since i’m currently on a trip. I will provide you further help  if needed in a week 😊

**Comment by InZan3** [comment]
Is it possible to run Pigpio with WiringPi at the same Time?
with sudo Homebridge i get this:
pi@raspberrypi:~ $ sudo homebridge
[8/15/2019, 7:47:48 PM] config.json (/root/.homebridge/config.json) not found.
[8/15/2019, 7:47:48 PM] Loaded plugin: homebridge-camera-rpi
[8/15/2019, 7:47:48 PM] Registering platform 'homebridge-camera-rpi.rpi-camera'
[8/15/2019, 7:47:48 PM] ---
[8/15/2019, 7:47:48 PM] Loaded plugin: homebridge-config-ui-x
[8/15/2019, 7:47:48 PM] Registering platform 'homebridge-config-ui-x.config'
[8/15/2019, 7:47:48 PM] ---
[8/15/2019, 7:47:48 PM] Loaded plugin: homebridge-gpio-device
homebridge-gpio-device API version: 2.4
[8/15/2019, 7:47:48 PM] Registering accessory 'homebridge-gpio-device.GPIODevice'
[8/15/2019, 7:47:48 PM] ---
[8/15/2019, 7:47:48 PM] Loaded plugin: homebridge-gpio-rgb-ledstrip
[8/15/2019, 7:47:48 PM] Registering accessory 'homebridge-gpio-rgb-ledstrip.SmartLedStrip'
[8/15/2019, 7:47:48 PM] ---
[8/15/2019, 7:47:48 PM] Loaded plugin: homebridge-raspberrypi-temperature
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/root/.homebridge/config.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at isConfig (/usr/local/lib/node_modules/homebridge-raspberrypi-temperature/index.js:20:32)
    at Plugin.module.exports [as initializer] (/usr/local/lib/node_modules/homebridge-raspberrypi-temperature/index.js:7:9)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:171:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:145:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)

**Comment by manfredipist** [comment]
Ok so, if you run homebridge as root you need to properly offer a config file in home folder so link your /home/pi/.homebridge/config.json file in /home/root/.homebridge/config.json ( use ln -s ) or directly copy the file in that folder. It will then work hopefully 😊

**Comment by InZan3** [comment]
I have found a Solution, instead of “chmod u+s /usr/bin/node” i have used “chmod u+s /usr/local/bin/node” and it work :-)
Now i have a new Problem, Pi Cam dosnt show a picture anymore^^

**Comment by manfredipist** [comment]
Well, I'm closing the issue since it has been solved, although it was not related to my plugin but rather to the usage of homebridge itself
